theme: Finansial
title: Uangtua
description: Aplikasi ini berguna untuk membantu pengguna dalam mengatur keuangan dan menabung untuk masa tua. Selain itu, aplikasi ini juga dapat menampilkan pie chart dan line chart dari data yang dimasukkan. 
